export const BuildingRegistry = {
  grass: {
    name: "Grass",
    cost: 0,
    size: 1,
    effects: {},
    description: "Clear land for building.",
  },
  house: {
    name: "House",
    cost: 60,
    size: 1,
    effects: { population: 2 },
    floatText: "+2 👥",
    description: "A small home for two citizens.",
  },
  shop: {
    name: "Shop",
    cost: 40,
    size: 1,
    effects: { happiness: -0.05 },
    floatText: "-0.05 😊",
    description:
      "Generates income. Provides 2 Retail jobs.",
    generatesIncome: true,
    incomeMultiplier: 1,
    jobSlots: 2,
    jobType: "Retail",
  },
  park: {
    name: "Park",
    cost: 100,
    size: 2,
    effects: { happiness: 0.2 },
    floatText: "+0.2 😊",
    description: "Boosts happiness. Provides 1 Groundskeeper job.",
    jobSlots: 1,
    jobType: "Groundskeeper",
  },
  university: {
    name: "University",
    cost: 1000,
    size: 3,
    effects: { population: -1, happiness: 0.5 },
    requirements: { population: 100 },
    floatText: "+0.5 😊 -1 👥",
    description:
      "Higher education. Provides 5 Academic jobs.",
    jobSlots: 5,
    jobType: "Academic",
  },
  market: {
    name: "Market",
    cost: 5000,
    size: 3,
    effects: {},
    requirements: { population: 250 },
    floatText: "MARKET BUILT",
    description:
      "Major commerce hub. Provides 10 Trade jobs.",
    generatesIncome: true,
    incomeMultiplier: 10,
    jobSlots: 10,
    jobType: "Trade",
  },
  tower: {
    name: "Tower",
    cost: 25000,
    size: 2,
    effects: { gridExpansion: 5 },
    requirements: { population: 500 },
    floatText: "MAP EXPANDED!",
    description: "A mystical tower. Provides 1 Wizard job.",
    jobSlots: 1,
    jobType: "Wizard",
  },
  policeStation: {
    name: "Police",
    cost: 500,
    size: 1,
    texture: "police-station",
    effects: { happiness: 0.1 },
    floatText: "STATION READY",
    description: "Reduces crime risk. Provides 3 Police jobs.",
    jobSlots: 3,
    jobType: "Police",
    safetyRadius: 6,
  },
  factory: {
    name: "Factory",
    cost: 800,
    size: 2,
    texture: "factory",
    effects: { happiness: -0.3 },
    requirements: { population: 30 },
    floatText: "PRODUCING...",
    description: "High income, but pollutes. Provides 8 Industrial jobs.",
    generatesIncome: true,
    incomeMultiplier: 5,
    jobSlots: 8,
    jobType: "Industrial",
  },
  office: {
    name: "Office",
    cost: 2000,
    size: 2,
    texture: "office-building",
    effects: { happiness: -0.1 },
    requirements: { population: 50 },
    floatText: "WORKING...",
    description: "Modern commerce. Provides 12 Corporate jobs.",
    generatesIncome: true,
    incomeMultiplier: 8,
    jobSlots: 12,
    jobType: "Corporate",
  },
  jail: {
    name: "Jail",
    cost: 1500,
    size: 2,
    texture: "jail",
    effects: { happiness: -0.2 },
    requirements: { population: 20 },
    floatText: "CELLS READY",
    description: "Holds up to 5 prisoners. Provides 4 Guard jobs.",
    jobSlots: 4,
    jobType: "Guard",
    prisonerCapacity: 5,
  },
  road: {
    name: "Road",
    cost: 10,
    size: 1,
    texture: "road-tile",
    effects: { happiness: 0.05 },
    description: "A path for citizens. Improves mobility.",
  },
  hospital: {
    name: "Hospital",
    cost: 5000,
    size: 2,
    texture: "hospital",
    effects: { happiness: 0.4 },
    requirements: { population: 150 },
    floatText: "+0.4 😊",
    description: "Medical care. Provides 6 Medical jobs.",
    jobSlots: 6,
    jobType: "Medical",
  },
  fireStation: {
    name: "Fire Station",
    cost: 1500,
    size: 1,
    texture: "fire-station",
    effects: { happiness: 0.2 },
    requirements: { population: 40 },
    floatText: "FIRE WATCH READY",
    description: "Protects the city. Provides 3 Firefighter jobs.",
    jobSlots: 3,
    jobType: "Firefighter",
  },
  library: {
    name: "Library",
    cost: 800,
    size: 1,
    texture: "library",
    effects: { happiness: 0.3 },
    requirements: { population: 25 },
    floatText: "+0.3 😊",
    description: "A place for study. Provides 2 Librarian jobs.",
    jobSlots: 2,
    jobType: "Librarian",
  },
  fountain: {
    name: "Fountain",
    cost: 200,
    size: 1,
    texture: "fountain",
    effects: { happiness: 0.15 },
    floatText: "+0.15 😊",
    description: "A beautiful decorative fountain.",
  },
  cinema: {
    name: "Cinema",
    cost: 10000,
    size: 2,
    texture: "cinema",
    effects: { happiness: 0.4 },
    requirements: { population: 200 },
    floatText: "SHOWTIME!",
    description: "Entertainment hub. Provides 4 Staff jobs.",
    generatesIncome: true,
    incomeMultiplier: 12,
    jobSlots: 4,
    jobType: "Staff",
  },
  restaurant: {
    name: "Restaurant",
    cost: 600,
    size: 1,
    texture: "restaurant",
    effects: { happiness: 0.2 },
    requirements: { population: 15 },
    floatText: "DINNER IS SERVED!",
    description: "Local dining. Provides 3 Chef jobs.",
    generatesIncome: true,
    incomeMultiplier: 4,
    jobSlots: 3,
    jobType: "Chef",
  },
  apartment: {
    name: "Apartment",
    cost: 5000,
    size: 2,
    texture: "apartment-block",
    effects: { population: 15 },
    requirements: { population: 100 },
    floatText: "+15 👥",
    description: "High-density housing for 15 citizens.",
  },
  supermarket: {
    name: "Supermarket",
    cost: 8000,
    size: 2,
    texture: "supermarket",
    effects: { happiness: 0.1 },
    requirements: { population: 300 },
    floatText: "GROCERIES!",
    description: "All-in-one shop. Provides 8 Clerk jobs.",
    generatesIncome: true,
    incomeMultiplier: 15,
    jobSlots: 8,
    jobType: "Clerk",
  },
  school: {
    name: "School",
    cost: 3000,
    size: 2,
    texture: "school",
    effects: { happiness: 0.2, population: -1 },
    requirements: { population: 60 },
    floatText: "+0.2 😊",
    description: "Elementary education. Provides 4 Teacher jobs.",
    jobSlots: 4,
    jobType: "Teacher",
  },
  bank: {
    name: "Bank",
    cost: 15000,
    size: 1,
    texture: "bank",
    effects: { happiness: -0.1 },
    requirements: { population: 400 },
    floatText: "FINANCE!",
    description: "Economic powerhouse. Provides 10 Banker jobs.",
    generatesIncome: true,
    incomeMultiplier: 25,
    jobSlots: 10,
    jobType: "Banker",
  },
  gym: {
    name: "Gym",
    cost: 2000,
    size: 1,
    texture: "gym",
    effects: { happiness: 0.2 },
    requirements: { population: 80 },
    floatText: "+0.2 😊",
    description: "Fitness center. Provides 2 Trainer jobs.",
    jobSlots: 2,
    jobType: "Trainer",
  },
  subway: {
    name: "Subway",
    cost: 20000,
    size: 1,
    texture: "subway-entrance",
    effects: { happiness: 0.1 },
    requirements: { population: 500 },
    floatText: "TRANSIT READY",
    description: "Mass transit station. Provides 4 Transit jobs.",
    jobSlots: 4,
    jobType: "Transit",
  },
};

export const getBuildingConfig = (type) => {
  return BuildingRegistry[type] || BuildingRegistry.grass;
};

export const isMultiTile = (type) => {
  const config = getBuildingConfig(type);
  return config.size > 1;
};
