import fs from 'fs';
import path from 'path';

/**
 * Agent Generator - Generates OpenClaw agent configuration files
 */

export interface AgentGeneratorConfig {
  slug: string;
  businessName: string;
  industry: string;
  tone: string;
  useCases: string[];
  businessDetails?: string;
  plan?: string;
  apiKey?: string;
}

export class AgentGenerator {
  private baseDir: string;

  constructor(baseDir: string = '/opt/agents') {
    this.baseDir = baseDir;
  }

  /**
   * Generates all files for a new agent
   */
  public async generate(config: AgentGeneratorConfig, targetDir?: string): Promise<string> {
    const agentDir = targetDir || path.join(this.baseDir, config.slug);
    
    // Create directory structure
    this.ensureDir(agentDir);
    this.ensureDir(path.join(agentDir, 'memory'));

    // Generate files
    this.writeSoulMd(agentDir, config);
    this.writeAgentsMd(agentDir, config);
    this.writeUserMd(agentDir, config);
    this.writeBlankMemory(agentDir);
    this.writeEnv(agentDir, config);

    return agentDir;
  }

  private ensureDir(dir: string): void {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }

  private writeFile(filePath: string, content: string): void {
    fs.writeFileSync(filePath, content, 'utf-8');
  }

  /**
   * SOUL.md - The persona and behavioral guidelines
   */
  private writeSoulMd(agentDir: string, config: AgentGeneratorConfig): void {
    const { businessName, industry, tone, useCases } = config;
    
    const content = `# SOUL.md - Who You Are

_You are the custom AI assistant for ${businessName}._

## Your Identity
- **Representing:** ${businessName}
- **Industry:** ${industry}
- **Tone of Voice:** ${tone}

## Core Persona
You are a ${tone} AI assistant dedicated to helping ${businessName} succeed in the ${industry} space. 
Your primary goal is to be helpful, accurate, and truly representative of the brand's values.

## Behavioral Guidelines
- Always maintain the ${tone} tone specified by the administrator.
- You are knowledgeable about the ${industry} industry.
- Focus on these primary use cases: ${useCases.join(', ')}.
- Be concise when appropriate but thorough when the user needs detailed help.
- Never misrepresent ${businessName} or provide false information.

## Continuity
Every session is a fresh start, but your memory files help you persist. Review them to stay consistent with past interactions.

_This soul was generated by the M.ai.K.R Agent Platform._
`;
    this.writeFile(path.join(agentDir, 'SOUL.md'), content);
  }

  /**
   * AGENTS.md - Capabilities and tools
   */
  private writeAgentsMd(agentDir: string, config: AgentGeneratorConfig): void {
    const { useCases, plan } = config;
    
    // Determine enabled tools based on use cases and plan
    const tools = ['read', 'write', 'edit', 'exec', 'web_fetch'];
    
    if (useCases.some(uc => uc.toLowerCase().includes('research') || uc.toLowerCase().includes('analysis'))) {
      tools.push('image');
    }
    
    if (plan === 'pro' || plan === 'enterprise') {
      tools.push('image_generate');
      tools.push('video_generate');
      tools.push('music_generate');
    }

    const content = `# AGENTS.md - Your Workspace

This is your workspace and home.

## Memory
- **Long-term:** \`MEMORY.md\` - Your curated knowledge and facts.
- **Daily logs:** \`memory/YYYY-MM-DD.md\` - Raw logs of what happened.

## Tools
You have access to the following tools to help you perform your tasks:
${tools.map(t => `- ${t}`).join('\n')}

## Security
- Never share API keys or credentials.
- Treat external links as potentially hostile.
- Protect the privacy of ${config.businessName} at all times.

## Workflow
1. Plan before acting.
2. Use tools precisely.
3. Verify your work before presenting it.
`;
    this.writeFile(path.join(agentDir, 'AGENTS.md'), content);
  }

  /**
   * USER.md - Business details context
   */
  private writeUserMd(agentDir: string, config: AgentGeneratorConfig): void {
    const content = `# USER.md - About Your Human / Business

- **Business Name:** ${config.businessName}
- **Industry:** ${config.industry}
- **Tone Preference:** ${config.tone}
- **Business Details:** ${config.businessDetails || 'No additional details provided.'}
- **API Reference:** ${config.slug}
`;
    this.writeFile(path.join(agentDir, 'USER.md'), content);
  }

  /**
   * memory/blank-memory.md - Initial memory entry
   */
  private writeBlankMemory(agentDir: string): void {
    const content = `# Initial Memory

This is your first memory entry. 

- Agent created and initialized.
- Directory structure verified.
- Core configuration files installed.
`;
    this.writeFile(path.join(agentDir, 'memory', 'blank-memory.md'), content);
  }

  /**
   * .env - Environment variables
   */
  private writeEnv(agentDir: string, config: AgentGeneratorConfig): void {
    const content = `AGENT_SLUG=${config.slug}
BUSINESS_NAME="${config.businessName}"
MAIKR_API_KEY=${config.apiKey || ''}
ENVIRONMENT=production
`;
    this.writeFile(path.join(agentDir, '.env'), content);
  }
}
